#!/usr/bin/env bash

echo "Yo fam, want name or nah?"
read appName

express --no-view $appName
cd $appName
git init

# install default dependencies
npm install nodemon@1.18 chai@4.1 chai-http@4.0 dotenv@6.0 forever@0.15 mocha@5.2 request@2.87 md5@2.2 http-errors@1.7 moment@2.22 body-parser@1.18 --save
npm audit fix

# create default dir and files
mkdir tests
mkdir helpers
mkdir services
mkdir "${appName}_modules"
mkdir middlewares
touch Dockerfile docker-compose.yml README.md .env
touch CHANGELOG.md

# add a title to README
echo "# ${appName}" >> README.md

# replace express's app.js with the company's own default app.js
rm app.js
curl -o app.js https://raw.githubusercontent.com/OD-International/express-boilerplate/master/app.js

# download MIT license
curl -o LICENSE https://raw.githubusercontent.com/OD-International/express-boilerplate/master/LICENSE

# download gitignore
curl -o .gitignore https://raw.githubusercontent.com/OD-International/express-boilerplate/master/gitignore

# clean out the default route implementation
rm -rf routes
mkdir routes
