#!/usr/bin/env bash

# check if ~/bin/ exist, if not create one
if test -d ~/bin/
then
    echo "Great, looks like you have ~/bin all setup already."
else
    mkdir ~/bin
    echo "Father...I crave Cheddar"
fi

# download script to the bin directory under the home diretory
curl -o ~/bin/opbanana https://raw.githubusercontent.com/OD-International/express-boilerplate/master/banana

# adds script to $HOME path
echo "export PATH="$HOME/bin:$PATH"" >> ~/.bash_profile

# make the script executable
chmod +x ~/bin/opbanana

# prompt success message
echo "
 ██████╗ ██████╗ ██████╗  █████╗ ███╗   ██╗ █████╗ ███╗   ██╗ █████╗ 
██╔═══██╗██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔══██╗████╗  ██║██╔══██╗
██║   ██║██████╔╝██████╔╝███████║██╔██╗ ██║███████║██╔██╗ ██║███████║
██║   ██║██╔═══╝ ██╔══██╗██╔══██║██║╚██╗██║██╔══██║██║╚██╗██║██╔══██║
╚██████╔╝██║     ██████╔╝██║  ██║██║ ╚████║██║  ██║██║ ╚████║██║  ██║
 ╚═════╝ ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
"

# some helpful message
echo 'to generate a new express app, simply run `opbanana`'

exit 0
